<?php if ( ! defined( 'ABSPATH' ) ) {
	die; } // Cannot access directly.

// Sticky Button Settings.
ATC::createSection(
	$prefix,
	array(
		'title'  => __( 'Sticky Button on Product Page', 'wk-add-to-cart-button-for-woocommerce' ),
		'icon'   => '',
		'fields' => array(
			array(
				'id'       => 'atc_sticky_show',
				'type'     => 'button_set',
				'title'    => __( 'Button Status', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Define the button status from here to show/hide', 'wk-add-to-cart-button-for-woocommerce' ),
				'help'     => __( 'The sticky button works only on product page.', 'wk-add-to-cart-button-for-woocommerce' ),
				'options'  => array(
					'show'        => __( 'Show', 'wk-add-to-cart-button-for-woocommerce' ),
					'hide'        => __( 'Hide', 'wk-add-to-cart-button-for-woocommerce' ),
					'show_mobile' => __( 'Show Only Mobile', 'wk-add-to-cart-button-for-woocommerce' ),
				),
				'default'  => 'show_mobile',
				'class'    => 'help-customization',
			),
			array(
				'id'         => 'atc_sticky_qty_show',
				'type'       => 'switcher',
				'title'      => __( 'Quantity Status', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'   => __( 'Define the status to show/hide the quantity field of simple products', 'wk-add-to-cart-button-for-woocommerce' ),
				'default'    => false,
				'text_on'    => __( 'Show', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_off'   => __( 'Hide', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_width' => 80,
			),
			array(
				'id'         => 'atc_sticky_variations_show',
				'type'       => 'switcher',
				'title'      => __( 'Variation Status', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'   => __( 'Define the status to show/hide the variation table of variable products', 'wk-add-to-cart-button-for-woocommerce' ),
				'default'    => false,
				'text_on'    => __( 'Show', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_off'   => __( 'Hide', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_width' => 80,
			),
			array(
				'id'         => 'atc_sticky_group_table_show',
				'type'       => 'switcher',
				'title'      => __( 'Group-table Status', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'   => __( 'Define the status to show/hide the group-table of grouped products', 'wk-add-to-cart-button-for-woocommerce' ),
				'default'    => false,
				'text_on'    => __( 'Show', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_off'   => __( 'Hide', 'wk-add-to-cart-button-for-woocommerce' ),
				'text_width' => 80,
			),

			array(
				'type'    => 'subheading',
				'content' => __( 'Common Options', 'wk-add-to-cart-button-for-woocommerce' ),
			),
			array(
				'id'       => 'atc_sticky_txt',
				'type'     => 'text',
				'title'    => __( 'Button Text', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the text for the sticky <strong>Add to Cart</strong> button', 'wk-add-to-cart-button-for-woocommerce' ),
				'default'  => 'Add to Cart',
			),
			array(
				'id'       => 'atc_sticky_icon',
				'type'     => 'icon',
				'title'    => __( 'Icon', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the icon for the sticky button', 'wk-add-to-cart-button-for-woocommerce' ),
			),
			array(
				'id'       => 'atc_sticky_icon_position',
				'type'     => 'button_set',
				'title'    => __( 'Icon Alignment', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the position of the icon inside the button text', 'wk-add-to-cart-button-for-woocommerce' ),
				'options'  => array(
					'before' => __( 'Before', 'wk-add-to-cart-button-for-woocommerce' ),
					'after'  => __( 'After', 'wk-add-to-cart-button-for-woocommerce' ),
				),
				'default'  => 'before',
			),
			array(
				'id'       => 'atc_sticky_btn_size_desktop',
				'type'     => 'dimensions',
				'title'    => __( 'Button Size on Desktop', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the width-height of the button for Desktop screen', 'wk-add-to-cart-button-for-woocommerce' ),
			),
			array(
				'id'       => 'atc_sticky_btn_size_mobile',
				'type'     => 'dimensions',
				'title'    => __( 'Button Size on Mobile', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the width-height of the button for Mobile Screen', 'wk-add-to-cart-button-for-woocommerce' ),
				'output'   => '#atc__btn-sticky button',
			),
			array(
				'id'       => 'atc_sticky_button_position',
				'type'     => 'select',
				'title'    => __( 'Button Position', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Define the button position from here', 'wk-add-to-cart-button-for-woocommerce' ),
				'options'  => array(
					'default'      => __( 'Default', 'wk-add-to-cart-button-for-woocommerce' ),
					'bottom-right' => __( 'Bottom Right', 'wk-add-to-cart-button-for-woocommerce' ),
					'bottom-left'  => __( 'Bottom Left', 'wk-add-to-cart-button-for-woocommerce' ),
					'top-right'    => __( 'Top Right', 'wk-add-to-cart-button-for-woocommerce' ),
					'top-left'     => __( 'Top Left', 'wk-add-to-cart-button-for-woocommerce' ),
				),
				'default'  => 'bottom-right',
			),
			array(
				'id'          => 'atc_sticky_margin',
				'type'        => 'spacing',
				'title'       => __( 'Margin', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'    => __( 'Set margin here to offset the button from other element', 'wk-add-to-cart-button-for-woocommerce' ),
				'top_icon'    => __( 'Top', 'wk-add-to-cart-button-for-woocommerce' ),
				'bottom_icon' => __( 'Bottom', 'wk-add-to-cart-button-for-woocommerce' ),
				'left_icon'   => __( 'Left', 'wk-add-to-cart-button-for-woocommerce' ),
				'right_icon'  => __( 'Right', 'wk-add-to-cart-button-for-woocommerce' ),
				'output'      => '#atc__btn-sticky',
				'output_mode' => 'margin',
				'default'     => array(
					'top'    => '10',
					'right'  => '10',
					'bottom' => '10',
					'left'   => '10',
					'unit'   => 'px',
				),
			),
			array(
				'id'          => 'atc_sticky_Padding',
				'type'        => 'spacing',
				'title'       => __( 'Padding', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'    => __( 'Set padding for the button text here', 'wk-add-to-cart-button-for-woocommerce' ),
				'top_icon'    => __( 'Top', 'wk-add-to-cart-button-for-woocommerce' ),
				'bottom_icon' => __( 'Bottom', 'wk-add-to-cart-button-for-woocommerce' ),
				'left_icon'   => __( 'Left', 'wk-add-to-cart-button-for-woocommerce' ),
				'right_icon'  => __( 'Right', 'wk-add-to-cart-button-for-woocommerce' ),
				'output'      => '#atc__btn-sticky button',
				'output_mode' => 'padding',
			),
			array(
				'id'           => 'atc_sticky_typography',
				'type'         => 'typography',
				'title'        => __( 'Button Typography', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'     => __( 'Set the font-family and font-styles for the button', 'wk-add-to-cart-button-for-woocommerce' ),
				'color'        => false,
				'subset'       => false,
				'preview_text' => __( 'Add to Cart', 'wk-add-to-cart-button-for-woocommerce' ),
				'output'       => '#atc__btn-sticky button',
			),
			array(
				'id'       => 'atc_sticky_color',
				'type'     => 'color_group',
				'title'    => __( 'Sticky Button Color', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Define the text color and background color for the buttons', 'wk-add-to-cart-button-for-woocommerce' ),
				'options'  => array(
					'color-txt'       => __( 'Color Text', 'wk-add-to-cart-button-for-woocommerce' ),
					'color-txt-hover' => __( 'Color Text on Hover', 'wk-add-to-cart-button-for-woocommerce' ),
					'color-bg'        => __( 'Color Background', 'wk-add-to-cart-button-for-woocommerce' ),
					'color-bg-hover'  => __( 'Color Background on Hover', 'wk-add-to-cart-button-for-woocommerce' ),
				),
			),
			array(
				'id'       => 'atc_sticky_border',
				'type'     => 'border',
				'title'    => __( 'Border', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the border width and style from here', 'wk-add-to-cart-button-for-woocommerce' ),
				'all_icon' => __( 'Size', 'wk-add-to-cart-button-for-woocommerce' ),
				'all'      => true,
				'color'    => false,
				'default'  => array(
					'all'   => '0',
					'style' => 'solid',
					'unit'  => 'px',
				),
			),
			array(
				'id'       => 'atc_sticky_border_color',
				'type'     => 'color_group',
				'title'    => __( 'Border Color', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Set the border color for normal and hover state', 'wk-add-to-cart-button-for-woocommerce' ),
				'options'  => array(
					'border-color' => __( 'Normal', 'wk-add-to-cart-button-for-woocommerce' ),
					'border-hover' => __( 'On Hover', 'wk-add-to-cart-button-for-woocommerce' ),
				),
			),
			array(
				'id'          => 'atc_sticky_border_radius',
				'type'        => 'border',
				'title'       => __( 'Border Radius', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle'    => __( 'Define the border-radius for the button\'s corner here', 'wk-add-to-cart-button-for-woocommerce' ),
				'left_icon'   => __( 'Top Left', 'wk-add-to-cart-button-for-woocommerce' ),
				'top_icon'    => __( 'Top Right', 'wk-add-to-cart-button-for-woocommerce' ),
				'bottom_icon' => __( 'Bottom Left', 'wk-add-to-cart-button-for-woocommerce' ),
				'right_icon'  => __( 'Bottom Right', 'wk-add-to-cart-button-for-woocommerce' ),
				'color'       => false,
				'style'       => false,
				'class'       => 'atc-no-placeholder',
			),
			array(
				'id'       => 'atc_sticky_transition',
				'type'     => 'spinner',
				'title'    => __( 'Transition Time', 'wk-add-to-cart-button-for-woocommerce' ),
				'subtitle' => __( 'Transition helps to load the color in hover stat smoothly. Define it here in micro-seconds', 'wk-add-to-cart-button-for-woocommerce' ),
				'unit'     => 'ms',
				'default'  => 300,
			),
		),
	)
);
